spring:
  datasource:
    url:jdbc:mysql:///springboot?serverTimezone=UTC
    username:root
    password:Jwj2004918
    driver-class-name:com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.pojo


